package com.app.awareness.data

/**
 * A single plain-English insight generated by [com.app.awareness.service.InsightEngine]
 * from the user's daily/weekly Room data combined with [BenchmarkData].
 *
 * Displayed as cards on HomeScreen (2–5 per day, horizontal scroll).
 *
 * Module 6 — BACKEND.md
 */
data class Insight(
    /** Insight category — use the [Type] constants. */
    val type: String,

    /** Plain English sentence shown directly to the user. */
    val message: String,

    /** Which metric triggered this insight — use the [Metric] constants. */
    val metric: String,

    /** Emotional tone of the insight — use the [Sentiment] constants. */
    val sentiment: String,
) {
    object Type {
        const val COMPARATIVE = "comparative"   // user vs world average
        const val ANOMALY     = "anomaly"       // unusual spike or drop
        const val PATTERN     = "pattern"       // recurring day-of-week behaviour
        const val STREAK      = "streak"        // N consecutive good/bad days
    }

    object Metric {
        const val SCREEN_TIME       = "screen_time"
        const val INSTAGRAM_OPENS   = "instagram_opens"
        const val SPOTIFY_MINUTES   = "spotify_minutes"
        const val NOTIFICATIONS     = "notifications"
        const val BEST_DAY          = "best_day"
    }

    object Sentiment {
        const val POSITIVE = "positive"
        const val NEUTRAL  = "neutral"
        const val WARNING  = "warning"
    }
}
